// <auto-generated />
using System;
using ConfigurationStuff.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfigurationStuff.Migrations
{
    [DbContext(typeof(DataContexts))]
    [Migration("20241223105416_TryingToFixConcurrencyIssues")]
    partial class TryingToFixConcurrencyIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfigurationStuff.DbModels.Account", b =>
                {
                    b.Property<Guid>("AccountUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthTokenAuthUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SessionUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeOfAccountCreation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountUnique");

                    b.HasIndex("AuthTokenAuthUnique");

                    b.HasIndex("SessionUnique");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.AuthToken", b =>
                {
                    b.Property<Guid>("AuthUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthUnique");

                    b.ToTable("AuthToken");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.ClientInstance", b =>
                {
                    b.Property<Guid>("ClientUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionUnique")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientUnique");

                    b.HasIndex("SessionUnique");

                    b.ToTable("ClientInstance");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.DelayCalc", b =>
                {
                    b.Property<Guid>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientInstanceClientUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommunicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DataIterations")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Delay")
                        .HasColumnType("time");

                    b.Property<string>("RequestType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("messageId");

                    b.HasIndex("ClientInstanceClientUnique");

                    b.ToTable("DelayCalc");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.Session", b =>
                {
                    b.Property<Guid>("SessionUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountUnique")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionCreated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionUnique");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.Account", b =>
                {
                    b.HasOne("ConfigurationStuff.DbModels.AuthToken", "AuthToken")
                        .WithMany()
                        .HasForeignKey("AuthTokenAuthUnique");

                    b.HasOne("ConfigurationStuff.DbModels.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionUnique");

                    b.Navigation("AuthToken");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.ClientInstance", b =>
                {
                    b.HasOne("ConfigurationStuff.DbModels.Session", null)
                        .WithMany("ClientInstance")
                        .HasForeignKey("SessionUnique")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.DelayCalc", b =>
                {
                    b.HasOne("ConfigurationStuff.DbModels.ClientInstance", "ClientInstance")
                        .WithMany("DelayCalcs")
                        .HasForeignKey("ClientInstanceClientUnique");

                    b.Navigation("ClientInstance");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.ClientInstance", b =>
                {
                    b.Navigation("DelayCalcs");
                });

            modelBuilder.Entity("ConfigurationStuff.DbModels.Session", b =>
                {
                    b.Navigation("ClientInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
